### ISSUE TITLE
项目中用到的base 库在哪里

### ISSUE THREAD

**Issue by cornflower10** [lulululbj/wanandroid#10]

**Comment by lulululbj** [comment]
出門右轉  [AndroidUtilCodeKTX](https://github.com/lulululbj/AndroidUtilCodeKTX)

**Comment by lulululbj** [comment]
@cornflower10 出门右转 [AndroidUtilCodeKTX](https://github.com/lulululbj/AndroidUtilCodeKTX)

**Comment by YellowMaple** [comment]
当前版本并没有引入anko包，会出现类似错误。
**H:\wanandroid-mvvm-kotlin\app\src\main\java\luyao\wanandroid\ui\collect\MyCollectActivity.kt: (45, 13): Unresolved reference: setOnRefreshListener**

**修复如下：**
```
ext.anko_version='0.10.8'
implementation "org.jetbrains.anko:anko:$anko_version"
```

**Comment by lulululbj** [comment]
> 当前版本并没有引入anko包，会出现类似错误。
> **H:\wanandroid-mvvm-kotlin\app\src\main\java\luyao\wanandroid\ui\collect\MyCollectActivity.kt: (45, 13): Unresolved reference: setOnRefreshListener**
> 
> **修复如下：**
> 
> ```
> ext.anko_version='0.10.8'
> implementation "org.jetbrains.anko:anko:$anko_version"
> ```

项目中并未使用 anko 库
