### ISSUE TITLE
关于看了代码第一点浅显理解

### ISSUE THREAD

**Issue by zizikoth** [lulululbj/wanandroid#11]
1.首页 Tab+ViewPager+Fragment
`FragmentPagerAdapter(supportFragmentManager, BEHAVIOR_RESUME_ONLY_CURRENT_FRAGMENT)`
这段代码的原意是让不可见的Fragment执行到onResume **之前** ，但是我发现BaseFragment的初始化操作全部都放在了onCreateView中 这样使得懒加载失效，那么这些初始化操作是否应该放在onResume中进行操作，使用变量控制判断是否初始化已完成

**Comment by lulululbj** [comment]
@zmemo 感谢反馈。当时发现原构造函数已废弃，就直接修改了，没有进行深入思考。后面等我确定问题后会进行修改。

**Comment by lulululbj** [comment]
> 1.首页 Tab+ViewPager+Fragment
> `FragmentPagerAdapter(supportFragmentManager, BEHAVIOR_RESUME_ONLY_CURRENT_FRAGMENT)`
> 这段代码的原意是让不可见的Fragment执行到onResume **之前** ，但是我发现BaseFragment的初始化操作全部都放在了onCreateView中 这样使得懒加载失效，那么这些初始化操作是否应该放在onResume中进行操作，使用变量控制判断是否初始化已完成

已替换 ViewPager2 。
