### ISSUE TITLE
关于处理 loading/success/failure 的操作

### ISSUE THREAD

**Issue by yang163email** [lulululbj/wanandroid#13]
作者大大写的很好，点赞！

我有一些短浅看法关于处理 loading/success/failure 的操作
我放在了这个仓库中 https://github.com/yang163email/AnotherEdenTool

使用类似于 kotlin 标准库中提供 Result 将 loading/success/failure 进行封装

**Comment by lulululbj** [comment]
@yang163email 其实我已经在该改造了。可以看看 LoginActivity 的处理，还没来得及全部修改。之前的版本，说实话，有点不是那么 MVVM

**Comment by yang163email** [comment]
嗯嗯，是滴，学习到了
