### ISSUE TITLE
结束loading状态可以这样加个finishBlock么

### ISSUE THREAD

**Issue by CK875430315** [lulululbj/wanandroid#14]
fun executeResponse(
    response: MyResponse<Any>, successBlock: () -> Unit,
    errorBlock: () -> Unit
    , finishBlock: () -> Unit
) {
    if (response.code == -1) {
        errorBlock()
    } else {
        successBlock()
    }
    finishBlock()
}

**Comment by lulululbj** [comment]
这样也可以，就是感觉可读性不是那么好。
项目正在重构，登录部分已完成。关于 loading 状态的处理可以参照 LoginViewModel 。
