### ISSUE TITLE
'commons-beanutils-1.8.0.jar' 在 AS 上引用不到, 该如何处理?

### ISSUE THREAD

**Issue by DQSecret** [lulululbj/wanandroid#16]
![image](https://user-images.githubusercontent.com/19892930/68176893-72b8de80-ffc1-11e9-8f33-c3fd609af187.png)

'https://jcenter.bintray.com/commons-beanutils/commons-beanutils/1.8.0/commons-beanutils-1.8.0.jar'.

**Comment by lulululbj** [comment]
多半网络问题。留个邮箱？
