### ISSUE TITLE
不错呢，每个viewModel都有_uiState和uiState，可否把变量声明放到BaseViewModel

### ISSUE THREAD

**Issue by jp1017** [lulululbj/wanandroid#20]
![image](https://user-images.githubusercontent.com/7868514/69597079-af677b00-103f-11ea-9f7a-54ddfb02f03d.png)

**Comment by lulululbj** [comment]
可以，但没有必要吧，而且有可能对应不同的 uiState

**Comment by jp1017** [comment]
相同的放base里，不同的话，子类单独定义就好了，并且大部分状态都是可以通用的吧

**Comment by lulululbj** [comment]
恩，大部分就是 loading ，success，fail 这几个状态，数据类可以考虑使用泛型。
的确是个好建议，谢谢 。

**Comment by jp1017** [comment]
变懒，哈哈哈，尴尬

**Comment by jp1017** [comment]
在子activity里uiState.observe监听也可以放baseActivity里的

**Comment by lulululbj** [comment]
uiState.observe 放在 base 里合适吗。。这个项目里大多一个页面就一个网络请求，如果一个 Activity 有多个请求，就会有多个 uiState 。还有感觉过度封装就影响可读性了。

**Comment by jp1017** [comment]
可读性和封装确实很难做好统一，可读性好的情况下，还是要少些代码
