### ISSUE TITLE
x5插件升级报重复引入错误，哪个插件还有用到x5呢

### ISSUE THREAD

**Issue by jp1017** [lulululbj/wanandroid#22]

**Comment by lulululbj** [comment]
网页浏览

**Comment by jp1017** [comment]
implemation里哪个还太依赖了x5呢

**Comment by lulululbj** [comment]
implementation files('libs/tbs_sdk_thirdapp_v3.6.0.1183_43604_sharewithdownload_withoutGame_obfs_20180211_105126.jar')

**Comment by jp1017** [comment]
你没听懂我意思尴尬了：

- implementation fileTree(include: ['*.jar'], dir: 'libs')
- implementation files('libs/tbs_sdk_thirdapp_v3.6.0.1183_43604_sharewithdownload_withoutGame_obfs_20180211_105126.jar')

注释掉上面两行，添加下面一行
+    implementation "com.tencent.tbs.tbssdk:sdk:43697"


就是升级x5，报错： 

## Program type already present: MTT.ThirdAppInfoNew

**Comment by lulululbj** [comment]
我把 lib 目录下的 jar 包删除之后，是可以正常编译的。

**Comment by jp1017** [comment]
去掉jar，然后去掉了那两行，新加了implementation "com.tencent.tbs.tbssdk:sdk:43697"吗，还是报错呢

**Comment by lulululbj** [comment]
implementation fileTree(include: ['*.jar'], dir: 'libs') 这一行我没有注释 。
