### ISSUE TITLE
这段代码为什么会执行两次，第一次拿到数据，第二次就是空的数据了

### ISSUE THREAD

**Issue by As00522038** [lulululbj/wanandroid#23]
![image](https://user-images.githubusercontent.com/34831218/69718221-c5149780-1148-11ea-9998-e124b4d96fcc.png)

**Comment by As00522038** [comment]
第一次是有数据的
<img width="550" alt="264f872d726e295622176054e0ffc59" src="https://user-images.githubusercontent.com/34831218/69719968-939dcb00-114c-11ea-812e-cc87b13e27c7.png">

第二次就是Unit了
<img width="558" alt="c644da7150ef56cdd3e7137abe20025" src="https://user-images.githubusercontent.com/34831218/69719972-97c9e880-114c-11ea-9cbb-1fe609857f89.png">

有点懵，为啥数据没了

**Comment by lulululbj** [comment]
可能协程的 debug 给你造成了假象，你可以通过打 log 的方式来证明只会执行一次。
第一次进断点应该是 executeResponse() 方法被调用，可以看到方法参数。
第二次进断点应该是进入协程吧，你看到的 $result 应该是返回值，
<img width="615" alt="捕获" src="https://user-images.githubusercontent.com/13194137/69768841-3d1ca500-11bd-11ea-8dc2-c036c7aded4d.PNG">
最后 debug 看到的返回值仍然是 Unit ，但是 `result is Result.Success` 执行结果是 true 。

**Comment by As00522038** [comment]
第一次看到的是进了子线程，第二次就主线程了，昨天检查代码，发现自己忘加了 CoroutineScope by MainScope()，然后就可以了，还是不太熟悉协程的使用，不过谢谢大佬了
