### ISSUE TITLE
协程写的网络请求思路非常清晰，但是有个问题，每个请求处理result，每次都要判断成功和失败，不大优雅呀

### ISSUE THREAD

**Issue by jp1017** [lulululbj/wanandroid#25]
每个请求都要判断成功失败，不大优雅呀

```
               if (result is Result.Success){
                    emitUiState(showProgress = false,showSuccess = result.data,enableShareButton = true)
                }else if (result is Result.Error){
                    emitUiState(showProgress = false,showError = result.exception.message,enableShareButton = true)
                }
```

**Comment by jp1017** [comment]
失败可以统一弹个吐司，每次返回不用处理，但是还是要判断是否成功

**Comment by lulululbj** [comment]
项目中不大可能对于任何失败都只是一个吐司，不用的 View 可能有不同的错误处理，和界面元素显示。个人觉得这里没必要做什么统一处理。

**Comment by jp1017** [comment]
是的，我的意思是每个页面除了判断成功和失败，还有没别的方案实现呢？

**Comment by lulululbj** [comment]
统一写个高阶函数都行，我以前就这么处理的，就是丧失了那么一点代码可读性。

    inline  fun <T : Any> checkResult(result: Result<T>, success:(T) -> Unit, error:(String?)->Unit){
        if (result is Result.Success) {
            success(result.data)
        } else if (result is Result.Error) {
            error(result.exception.message)
        }
    }

使用起来就这样，

                checkResult(result,{
                    emitUiState(showSuccess = it, enableLoginButton = true)
                },{
                    emitUiState(showError = it , enableLoginButton = true)
                })

我是觉得可读性不大好，用 dsl 可能好一些。所以我比较倾向于直接 if  else ，其实也没多麻烦

**Comment by jp1017** [comment]
是的，感谢回复，回调的方式不是很优雅了，就用现在的吧
