### ISSUE TITLE
wanandroid有些接口返回的data是null， 比如退出登录和收藏。我看了下你的代码，也没有处理，但是却能执行，怎么回事

### ISSUE THREAD

**Issue by cmk0330** [lulululbj/wanandroid#26]

**Comment by lulululbj** [comment]
这的确是个问题。。
请求是发出去了的，只是解析 Response 的出错了，
```
java.lang.IllegalArgumentException: Parameter specified as non-null is null
```

由于 safeApiCall 中做了异常捕获，所以并没有什么影响。

```kotlin
    suspend fun <T : Any> safeApiCall(call: suspend () -> Result<T>, errorMessage: String): Result<T> {
        return try {
            call()
        } catch (e: Exception) {
            // An exception was thrown when calling the API so we're converting this to an IOException
            Result.Error(IOException(errorMessage, e))
        }
    }
```

你在 catch 分支打断点，实际上返回的是 Result.Error(）

**Comment by cmk0330** [comment]
> 这的确是个问题。。
> 请求是发出去了的，只是解析 Response 的出错了，
> 
> ```
> java.lang.IllegalArgumentException: Parameter specified as non-null is null
> ```
> 
> 由于 safeApiCall 中做了异常捕获，所以并没有什么影响。
> 
> ```kotlin
>     suspend fun <T : Any> safeApiCall(call: suspend () -> Result<T>, errorMessage: String): Result<T> {
>         return try {
>             call()
>         } catch (e: Exception) {
>             // An exception was thrown when calling the API so we're converting this to an IOException
>             Result.Error(IOException(errorMessage, e))
>         }
>     }
> ```
> 
> 你在 catch 分支打断点，实际上返回的是 Result.Error(）

**Comment by cmk0330** [comment]
那如果要是数据返回null并且还想收到请求成功的通知，怎么弄。还有safeApiCall（）中errormessage是自己定义的，能不能让errormessage自动接收错误信息？我才学kotlin不久，这里有点搞不懂

**Comment by lulululbj** [comment]
要么后台不要返回 null ，要么使用可空类型。
关于这里的 errorMessage ，和后台返回的错误信息并不相干。之前的 issue 里回答过， #24
