### ISSUE TITLE
如果我想在viewModel里获取json中的code和msg，该如何获取呢？

### ISSUE THREAD

**Issue by hardgit** [lulululbj/wanandroid#27]
如题！

**Comment by lulululbj** [comment]
```kotlin
data class WanResponse<out T>(val errorCode: Int, val errorMsg: String, val data: T)
```

Repository 层就可以获取 Response。

**Comment by hardgit** [comment]
![图片](https://user-images.githubusercontent.com/31436497/70698107-c07fdf80-1d01-11ea-8a13-2f52fb22fbb1.png)
如果在Repository 层更改返回，这样的话改动会不会有点大？
