### ISSUE TITLE
问个问题,我看你项目中用到了koin依赖注入用来初始化viewmodel

### ISSUE THREAD

**Issue by 424385117** [lulululbj/wanandroid#32]
问个问题,我看你项目中用到了koin依赖注入用来初始化viewmodel,我项目中直接用反射初始化viewmodel,就是BaseViewModel中直接初始化子类的ViewModel对象,两者性能有差别吗?用反射直接就父类生成了,子类直接调用,省了很多代码

**Comment by 424385117** [comment]
```
internal interface ViewModelInterface<VM : BaseViewModel> {
    var mViewModel: VM
    fun registerViewModel() {
        mViewModel = ViewModelProvider(this as ViewModelStoreOwner).get(
            Class.forName(
                (this.javaClass.genericSuperclass as ParameterizedType)
                    .actualTypeArguments[0].toString().split(" ")[1]
            ) as Class<VM>
        )
    }
}
```

这是我的代码,继承一下就好了

**Comment by DaveBoy** [comment]
我也用的这种方式   只不过区别在于我用的by lazy,性能上肯定有区别  但是我觉得应该不是特别大

**Comment by 424385117** [comment]
> 我也用的这种方式 只不过区别在于我用的by lazy,性能上肯定有区别 但是我觉得应该不是特别大

by lazy 的话,每个基类都得写,我这基类有点多有5个

**Comment by DaveBoy** [comment]
```
protected val viewModel: VM by lazy {
        initVM()
    }
    private fun initVM(): VM {
        return ViewModelProvider(this).get(getVmClazz(this) as Class<VM>)
    }
```
不就一个吗

**Comment by 424385117** [comment]
> ```
> protected val viewModel: VM by lazy {
>         initVM()
>     }
>     private fun initVM(): VM {
>         return ViewModelProvider(this).get(getVmClazz(this) as Class<VM>)
>     }
> ```
> 
> 不就一个吗

你的getVmClazz是怎么写的

**Comment by DaveBoy** [comment]
跟你的差不多
