### ISSUE TITLE
navigation replace每次都重新初始化？

### ISSUE THREAD

**Issue by DaveBoy** [lulululbj/wanandroid#33]
有没有处理方案？

**Comment by DaveBoy** [comment]
除了vp之外

**Comment by lulululbj** [comment]
关于 Navigation 的应用场景，Google 也给过解释：

> Navigation focuses on elements that affect the back stack and tabs do not affect the back stack - you should continue to manage tabs with a ViewPager and TabLayout

所以主页 Tab 这种场景，或者所有会因为 replace 造成影响的地方，都不是 Navigation 的应用场景。如果硬要用，当然也是可以的，重写 Navigator 或者 多个 NavController 。两种方案都有现成的实现。

https://github.com/STAR-ZERO/navigation-keep-fragment-sample ,这是重写 Navigator 的实现，回退栈可能会有问题。

https://github.com/android/architecture-components-samples/tree/master/NavigationAdvancedSample ，这是 Google 的示例，多 NavController ，解决了回退栈的问题。Google 自己有吐槽这种做法。

所以，问题可以解决，只是没有必要为了用 Navigation 而去用。
