### ISSUE TITLE
请教一个问题在一个activity中的两个fragment用了同一个viewmodel

### ISSUE THREAD

**Issue by Asher-0608** [lulululbj/wanandroid#36]
但是是两个不同的vm对象，请问这个问题是getviewmode（）这个方法导致的嘛？请问该怎么解决

**Comment by lulululbj** [comment]
使用 koin 的话，koin 有提供 `by sharedViewModel()` & `getSharedViewModel()` 。
不使用 koin 的话，使用 上层 Activity 的 context 就可以了。

**Comment by Asher-0608** [comment]
非常感谢，当时选择用koin的原因是可以简化这个获取vm的过程嘛？但感觉额外写一个appModule类反而有些繁琐了
