### ISSUE TITLE
为什么网络接口返回的不是 Call<*> ?

### ISSUE THREAD

**Issue by Mcl-123** [lulululbj/wanandroid#41]

**Comment by Mcl-123** [comment]
已经找到了，是Retrofit 2.6.0 支持协程的写法，建议更新下 Readme，谢谢~

**Comment by lulululbj** [comment]
> 已经找到了，是Retrofit 2.6.0 支持协程的写法，建议更新下 Readme，谢谢~

谢谢提醒，Readme 的确需要更新了。
