### ISSUE TITLE
关于把网络请求丢在Repository层

### ISSUE THREAD

**Issue by skyshenfu** [lulululbj/wanandroid#42]
兄弟你好，拜读了代码，有一个疑问
把网络请求丢在Repository层该怎么取消网络请求呢
看您的代码是在Repository处理网络请求，VM把请求数据转化为LiveData
类似于之前call.cancel()或者Rxjava中取消观察这种

**Comment by lulululbj** [comment]
viewModel 中配合协程作用域，根据绑定的生命周期对象进行取消。比如，Activity 中点击返回键，协程就会自动取消。

**Comment by 8debug** [comment]
> 兄弟你好，拜读了代码，有一个疑问
> 把网络请求丢在Repository层该怎么取消网络请求呢
> 看您的代码是在Repository处理网络请求，VM把请求数据转化为LiveData
> 类似于之前call.cancel()或者Rxjava中取消观察这种

东哥又回来搞代码了

**Comment by skyshenfu** [comment]
@skyshenfu
