### ISSUE TITLE
异常处理的问题

### ISSUE THREAD

**Issue by SoulThinker** [lulululbj/wanandroid#44]
大佬，请教个问题。。

`    suspend fun login(@Field("username") userName: String, @Field("password") passWord: String): WanResponse<User>` 

这么写的话，我想根据401，403的错误码进行特定提示或者后续操作，该怎么捕捉这种http异常呢

是在safeApiCall的try,catch中，if(e is HttpException)这样吗。

**Comment by lulululbj** [comment]
没记错的话，retrofit 里面协程那一块，对 非 2xx 的状态码是直接抛出异常的。我没处理过这种情况，你可以测试一下。
