### ISSUE TITLE
buildSrc 一直找不到依赖 

### ISSUE THREAD

**Issue by ForgetSky** [lulululbj/wanandroid#46]
buildSrc 一直找不到依赖 

Could not get unknown property 'Versions' for extension 'android' of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension.

各种重启，清缓存都没用 ，androidstudio4.0   gradle 6.1.1  kotlin1.3.72

**Comment by lulululbj** [comment]
拉取最新提交试一下。

**Comment by 1024477951** [comment]
buildSrc真的很奇怪，一直sync不成功，怎么清缓存都没用，但是删除项目重新拉取又可以了，然后你什么都没改一重启电脑打开又是一样的结果，坑得一批，请教下是什么情况

**Comment by zhongya666** [comment]
我也遇到了这个问题
