### ISSUE TITLE
[Build Error] Unresolved reference: liveData

### ISSUE THREAD

**Issue by JimmyYanDev** [lulululbj/wanandroid#5]
Android Studio : 3.4.1
Gradle: com.android.tools.build:gradle:3.4.2
Kotlin: ext.kotlin_version = '1.3.31'
Error Message:
luyao/wanandroid/ui/home/HomeViewModel.kt 
(23, 45): Unresolved reference: liveData
(24, 21): Suspend function 'withContext' should be called only from a coroutine or another suspend function
(25, 9): Unresolved reference: emit

**Comment by JimmyYanDev** [comment]
![image](https://user-images.githubusercontent.com/19723859/61699649-dd753f80-ad6d-11e9-9e07-593c2ada524f.png)

**Comment by lulululbj** [comment]
> Android Studio : 3.4.1
> Gradle: com.android.tools.build:gradle:3.4.2
> Kotlin: ext.kotlin_version = '1.3.31'
> Error Message:
> luyao/wanandroid/ui/home/HomeViewModel.kt
> (23, 45): Unresolved reference: liveData
> (24, 21): Suspend function 'withContext' should be called only from a coroutine or another suspend function
> (25, 9): Unresolved reference: emit

尝试了一下 livedata-ktx，忘记提交 gradle 文件了。添加如下依赖即可：

```
implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.2.0-alpha02'
```

以后尽量在 dev 分支作修改，无错误后再合并过来。

**Comment by JimmyYanDev** [comment]
感谢，问题已解决。
