### ISSUE TITLE
线程堆栈大小调整

### ISSUE THREAD

**Issue by 626838956** [lulululbj/wanandroid#50]
大佬，看到你的公众号文章OOM优化，评论中有提到线程优化的两个方案：
1. 使用xhook减小pthread_attr_setstacksize，设置线程堆栈缩小一半
2. 监控应用线程数和堆栈信息。在OOM时上报吗？
能帮帮详细说说吗？特别是xhook修改线程大小，找到了xhook的demo，不知道怎么写。有这块的代码就最好了。

**Comment by lulululbj** [comment]
> 大佬，看到你的公众号文章OOM优化，评论中有提到线程优化的两个方案：
> 
> 1. 使用xhook减小pthread_attr_setstacksize，设置线程堆栈缩小一半
> 2. 监控应用线程数和堆栈信息。在OOM时上报吗？
>    能帮帮详细说说吗？特别是xhook修改线程大小，找到了xhook的demo，不知道怎么写。有这块的代码就最好了。

我好像没有写过性能优化相关文章，可以给我看一下链接，我也学习一下

**Comment by 626838956** [comment]
看到的是鸿洋大佬的公众号，对应的wanandorid项目不是这个？
