### ISSUE TITLE
找不到下面的4个文件。

### ISSUE THREAD

**Issue by fzx19910714** [lulululbj/wanandroid#51]
ERROR: Could not find luyao.plugin.classfixer:classfixer:1.0.0.
Searched in the following locations:
    https://dl.google.com/dl/android/maven2/luyao/plugin/classfixer/classfixer/1.0.0/classfixer-1.0.0.pom
    https://dl.google.com/dl/android/maven2/luyao/plugin/classfixer/classfixer/1.0.0/classfixer-1.0.0.jar
    https://jcenter.bintray.com/luyao/plugin/classfixer/classfixer/1.0.0/classfixer-1.0.0.pom
    https://jcenter.bintray.com/luyao/plugin/classfixer/classfixer/1.0.0/classfixer-1.0.0.jar

why ?can't find locations

**Comment by lulululbj** [comment]
注释掉吧，我本地测试写的 gradle plugin，或者你本地生成一下。

**Comment by fzx19910714** [comment]
我本地如何生成？你可以先放仓库开源吗？
我具体不懂这些plugin的作用，不懂如何生成，麻烦了




            
            
                
                    
                            
                                
                            
                            
                                543062959
                            
                    
                        
                            
                                    邮箱：543062959@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


在2020年10月21日 22:17，luyao 写道： 
注释掉吧，我本地测试写的 gradle plugin，或者你本地生成一下。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/lulululbj/wanandroid/issues/51#issuecomment-713610237",
"url": "https://github.com/lulululbj/wanandroid/issues/51#issuecomment-713610237",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by lulululbj** [comment]
[remove gradle plugin](https://github.com/lulululbj/wanandroid/commit/ee8289d88df7acc9172aab9d33dd6b21c44b7612) ，拉取最新代码即可。
