### ISSUE TITLE
编译错误Could not find luyao.util.ktx:AndroidUtilKTX:0.0.4.

### ISSUE THREAD

**Issue by small-dream** [lulululbj/wanandroid#6]
Could not find luyao.util.ktx:AndroidUtilKTX:0.0.4.

**Comment by lulululbj** [comment]
> Could not find luyao.util.ktx:AndroidUtilKTX:0.0.4.

https://jcenter.bintray.com/luyao/util/ktx/AndroidUtilKTX/0.0.4/ ，这个版本还在，应该不会找不到呀。

**Comment by small-dream** [comment]
原因找到了，我用了阿里的镜像。。。不过运行时 liveData找不到了。。

**Comment by lulululbj** [comment]
> 原因找到了，我用了阿里的镜像。。。不过运行时 liveData找不到了。。

这个是我的锅，尝试了一下 livedata-ktx，忘记提交依赖了。

implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.2.0-alpha02'
