### ISSUE TITLE
异常处理

### ISSUE THREAD

**Issue by small-dream** [lulululbj/wanandroid#7]
我在使用中 发现 无网络情况下会奔溃 ，搜了一下
建议使用 runCatching{
}

包裹请求代码
通过 result 返回异常 做处理

**Comment by lulululbj** [comment]
> 我在使用中 发现 无网络情况下会奔溃 ，搜了一下
> 建议使用 runCatching{
> }
> 
> 包裹请求代码
> 通过 result 返回异常 做处理

老哥，心有灵犀，本地代码刚 runCatching 了一部分。在 Retrofit 的 issue 下也看到了这个问题，应该是和 Retrofit 的协程扩展有关，还没找到原因，暂时就先 runCatching 处理一下。
