### ISSUE TITLE
关于 Retrofit 2.6.0 对协程的支持

### ISSUE THREAD

**Issue by shortybin** [lulululbj/wanandroid#8]
看了下代码一直没看明白怎么把 Retrofit 返回的 Call 转换为具体的实体类，后来查了下是 Retrofit 2.6.0 添加了对协程的支持，可以直接返回了，可以在 README 更新说明下。

**Comment by lulululbj** [comment]
> 看了下代码一直没看明白怎么把 Retrofit 返回的 Call 转换为具体的实体类，后来查了下是 Retrofit 2.6.0 添加了对协程的支持，可以直接返回了，可以在 README 更新说明下。

恩，README 还是 init commit 的时候写的，后来一直没改过，有空我来补充一下。关于 Retrofit 2.6.0 写过一篇文章说明，https://juejin.im/post/5d0793616fb9a07eac05d407
