### ISSUE TITLE
就Retrofit协程有些问题请教

### ISSUE THREAD

**Issue by AndyYang2014** [lulululbj/wanandroid#9]
在用协程替换RxJava的情况下，协程有相关api能做到例如RxJava zip处理多个网络请求、retryWhen处理错误重试吗？

**Comment by lulululbj** [comment]
> 在用协程替换RxJava的情况下，协程有相关api能做到例如RxJava zip处理多个网络请求、retryWhen处理错误重试吗？

协程是为了解决异步问题，而 RxJava 并不仅仅是为了解决异步问题。协程没有办法完全的代替 RxJava，应该也不会提供类似 RxJava 这些的关键字。zip 的话，协程本身就是写的同步代码，不需要 zip 也可以。错误重试的话应该是由开发者自己来处理。
